apiVersion: v1
kind: Secret

metadata:
  name: base-secret-env
  namespace: base-namespace

data:
  DB_USER: ${vault:apps/demo-webserver@DB_USER | base64}
  DB_PASSWORD: ${vault:apps/demo-webserver@DB_PASSWORD | base64}

type: Opaque
